# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 15e6a5af1abd27376075fb3cbbad8a459bd0124959c3eb9a9cde35630edb9c90acfdb37a14ff94e7dce6eedf0d96443b589bdb8f88fbdc59b5225ccd3052299a

test:
  secret_key_base: 952afda7b61029c686052b3c8887af959cb60451756c06cb310e95fe29af8b33dbd0d9f05fb99871e8151a3f1d6910f529bb6493da2727e0f6fba14b067d30f8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
